name: Auto Deploy to Production

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy and Health Check
        runs-on: ubuntu-latest

        steps:
            - name: Deploy app to server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  script: |
                      echo "🔐 Writing .env.prod file..."
                      echo "${{ secrets.ENV_FILE }}" > ${{ secrets.PROJECT_ROOT_DIR }}/${{ github.event.repository.name }}/.env.prod

                      echo "📦 Pulling latest code..."
                      cd ${{ secrets.PROJECT_ROOT_DIR }}/${{ github.event.repository.name }}
                      git pull origin master

                      echo "🐳 Rebuilding and restarting Docker Compose service..."
                      cd ${{ secrets.PROJECT_ROOT_DIR }}/docker-config
                      docker compose -p st up -d --build ${{ github.event.repository.name }}
